### ISSUE TITLE
We should inform the user if they requested species properties that are not available

### ISSUE THREAD

**Issue by pbauman** [libantioch/antioch#1]
Hit this with Sutherland. It happily gave me N2 and did not scream that it didn't populate the other species in the requested species_list. That's not very nice.

**Comment by SylvainPlessis** [comment]
Isn't it done?  Can you check that it screams appropriately and close the issue if it's at your taste?

**Comment by pbauman** [comment]
Yup. It died when I tried C3 the first time. Thanks!

**Comment by pbauman** [comment]
This was resolved as part of the parsing refactoring.
