### ISSUE TITLE
Fix GSL/build system

### ISSUE THREAD

**Issue by pbauman** [libantioch/antioch#110]
1. GSL should be optional - I got a configure error when trying to configure without GSL.
2. Adding GSL, make check is failing to build the spliner test correctly. Probably not passing all the flags correctly.

Will get to this after AnitochCon2015 is over with...

**Comment by SylvainPlessis** [comment]
--without-gsl works as expected on my system

**Comment by SylvainPlessis** [comment]
By the way, should we indeed not pass the tests if GSL is not here or should we make them skipped tests?
I'd prefer the latest version.

**Comment by pbauman** [comment]
> --without-gsl works as expected on my system

Damn, really? That didn't configure for me. I'll play with this tonight.

**Comment by roystgnr** [comment]
Configured and passed make check for me.  Which has me pretty damn suspicious; there should have been skipped or failed checks.  I may try actually uninstalling GSL and see what happens.

**Comment by roystgnr** [comment]
Ha, never mind.  Didn't notice that I'd passed fewer tests than before.  The tests are disabled, not just skipped.

**Comment by pbauman** [comment]
I think I have a handle on what's going on and will fix later tonight. I think y'all have gsl-config in your path, even without the module (i.e. /usr/bin/gsl-config). I don't so the AC_MSG_ERROR gets tripped even though it's not a required package. Also, I'll update the tests to show SKIPPED when GSL is not installed.

**Comment by SylvainPlessis** [comment]
Do it also for the *stat_mech_thermo_unit_eigen*, I just followed this example and it's not very satisfying when actually thinking about it…

**Comment by SylvainPlessis** [comment]
Is this issue still relevant?

**Comment by pbauman** [comment]
yes. Haven't been able to get the time to fix it yet. Please leave open.
