### ISSUE TITLE
Can we make XMLParser::Troe() const?

### ISSUE THREAD

**Issue by pbauman** [libantioch/antioch#126]
The ChemKin version is const (out of necessity I see) leading to warnings that the base wasn't. However, as the XML version is coded right now, it can't be const. @SylvainPlessis, anyway to make this const on the top of your head before I dig through the code? This was the last warning for me to clear up.

**Comment by pbauman** [comment]
Err, the base version was const, only the XMLParser wasn't.

```
warning: ‘bool Antioch::ParserBase<NumericType>::Troe() const [with NumericType = double]’ was hidden [-Woverloaded-virtual]
          virtual bool Troe() const  {not_implemented(); return false;}

[snip]

 warning:   by ‘bool Antioch::XMLParser<NumericType>::Troe() [with NumericType = double]’ [-Woverloaded-virtual]
   bool XMLParser<NumericType>::Troe()

```

**Comment by SylvainPlessis** [comment]
Alright so the situation here:
  - ```XMLParser``` during the Troe() operation sets the pointer *_Troe* to the correct value, so the method cannot be _const_.
  - ```ChemKinParser``` is caching all the information at the *bool reaction()* method level, therefore *bool Troe() const* is but a retrieving of the info and can be _const_.  As I _const_ methods as much as I can. I just went for it.
  - ```ParserBase```do not have a _bool Troe() const_ method…  What is the compiler trying to say?

I forgot this issue, the answer is to do with ```XMLParser``` as ```ChemKinParser``` parser does, which means retrieving all the info at the very beginning in the *bool reaction()* method.  For historical reason, the xml was written before chemkin and it was just easier to read along non _const_ than to process everything at one place, it is not the case.

If someone wants to go for it, good (and good luck), if not, I'll start on it next week.

**Comment by pbauman** [comment]
> XMLParser during the Troe() operation sets the pointer _Troe to the correct value, so the method cannot be const.

Sorry for not being clear, but this was the crux of my question: can we modify the parsing algorithm to figure that if Troe should be true/false and make Troe() a const accessor?

**Comment by SylvainPlessis** [comment]
> Sorry for not being clear, but this was the crux of my question: can we modify the parsing algorithm to figure that if Troe should be true/false and make Troe() a const accessor?

Yep it's possible, and it will be done.  The principle is to set all the reaction in the method _bool reaction()_.  *_Troe* for instance will be *NULL* or pointing to the correct xml child.  Then 
_bool Troe()_ will become
```
bool Troe() const {return _rate_constant && _Troe;}
```

Is is clearer?

**Comment by pbauman** [comment]
Ah, OK, perfect. I'll let you take care of this then when you have a chance. It can be its own PR to 0.3.0-release.

**Comment by SylvainPlessis** [comment]
The branch was merged , it was answered, I'm closing it.
