### ISSUE TITLE
Disable offending vec tests when Travis+Clang = true?

### ISSUE THREAD

**Issue by pbauman** [libantioch/antioch#152]
@ddemidov pointed out the following in #149:
> Is it possible to disable specific tests based on environment variables (There is [TRAVIS=true](http://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables) for example)?

I bet we could add some sauce to the configure checks. Say check for `TRAVIS` in the environment and `AC_DEFINE(IS_TRAVIS)`. Further, check the value of `CC` and `AC_DEFINE(IS_CLANG)`. Then, we could do the usual automake workaround and skip whatever tests are killing Travis during `make check`. This way, we'd still run all the tests with GCC+VexCL and get some Clang+VexCL. But would lose the coverage of Clang without VexCL. Maybe two different builds - one with VexCL and one without?

**Comment by ddemidov** [comment]
Why do you differentiate between gcc and clang? They both fail to compile kinetics_regression_vec (at least): https://travis-ci.org/ddemidov/antioch/builds/67556456.

**Comment by pbauman** [comment]
Because I didn't pay attention. :) Thanks for pointing that out. I thought clang was the only problem child.

**Comment by pbauman** [comment]
Closing this (should've been closed a long time ago). Hopefully my CI server will be setup soon (the server is here, the CI part is still needed) and we can have VexCL enabled tests running there.
