### ISSUE TITLE
Add more data points to StockmayerPotential?

### ISSUE THREAD

**Issue by pbauman** [libantioch/antioch#156]
In testing with GRINS, I'm getting GSL interpolation errors because the temperature is falling outside the acceptable range during Newton convergence. I'm going to add an extrapolation bit for now, but I wonder if the better long term solution is to just add new values for interpolating since we could compute the values (doing quadrature on the required integrals).

**Comment by variscarey** [comment]
Didn't Sylvain add a patch to extrapolate the collision integrals for high
values of the reduced temperature T*?  It should only be a problem for
hydrogen and other light species, and I thought he interpolated the table
using the asymptotic  values of the collision integrals.  Did this not get
added to master?  Which collision integral is failing?

Varis

**Comment by pbauman** [comment]
@SylvainPlessis can chime in, but:

> Didn't Sylvain add a patch to extrapolate the collision integrals for high values of the reduced temperature T*?

AFAICT, no.

>  It should only be a problem for hydrogen and other light species,

This is happening during a Newton iteration for N and N2 (N2 recombination) for steady state flow (low Mach). During the Newton iteration, T spikes to > 9000K (not sure what the T* would be). So it's not really physical, but is affecting my ability to get convergence (I get convergence with other, simpler transport models).

> and I thought he interpolated the table using the asymptotic values of the collision integrals.

I'm not entirely sure, but it looks like he just pulled data from a paper (I don't have the citation handy) that reports the values of the collision integrals for a several points (using numerical quadrature IIRC) and we interpolate those.

> Which collision integral is failing?

I'm not sure. It's happening during the viscosity calculation, but it's either N or N2.

**Comment by variscarey** [comment]
Look at
void StockmayerPotential<CoeffType>::extrapolate_to(const StateType & T)

in
https://github.com/SylvainPlessis/antioch/blob/master/src/transport/include/antioch/stockmayer_potential.h

Doesn't look like it is in the release version yet.

Varis

**Comment by pbauman** [comment]
Damn. I'm not sure what happened. I see it in master (781c372c), but somehow that commit isn't in the 0.3.0-release branch. I'll see if I can sort this out. Thanks @variscarey this looks like the functionality I wanted. I was going to add it a lower level in the GSL stuff itself --- just do a linear extrapolation beyond the range that was given if the domain error GSL flag was given back to us. I still might do that, but I want to sort out why this isn't in the release branch.

**Comment by pbauman** [comment]
Closing this out. I see what happened and am [moving the discussion](https://groups.google.com/forum/#!topic/antioch-devel/S6-cv-GVcPQ) to antioch-devel. Thanks again @variscarey.
