### ISSUE TITLE
KineticsTheory::mu_and_k_and_D naming

### ISSUE THREAD

**Issue by pbauman** [libantioch/antioch#157]
As mentioned [here](https://groups.google.com/forum/#!topic/antioch-devel/S6-cv-GVcPQ), we need to rename D for forward compatibility or in order to support 3 different versions of computing mixture averaged diffusion coeffcients; currently, we only support one. The mixing part is currently contained in `WilkeTransportEvaluator::diffusion_mixing_rule`. This is hidden from the user, so we can refactor that easily. But how do we want the user to differentiate between the different models? Should we add a separate `WilkeTransportEvaluator::mu_and_k_and_D` call for each of the 3 different `D` models? Should we have, instead, the user pass an `enum` and do a switch underneath to call the right mixing model? Other suggestions?

In absence of other (probably better) suggestions, I'm kind of leaning towards the enum approach since 
1. We could leave the API as is (in the 0.3.0-redux branch) and then add new models, with the default enum being the current implementation, i.e. easy backward compatibility.
2. Everything can still be resolved at compile time.

I want to settle on this naming before tagging 0.3.0 so we don't have to potentially change the API to support all the models in the future.

**Comment by roystgnr** [comment]
Separate calls are more efficient, but only infinitesimally so, and they make the API even more of a PITA.  Enum approach is okay with me.

**Comment by pbauman** [comment]
Thanks @roystgnr. I'll consider this issue settled then and proceed.

**Comment by pbauman** [comment]
Added the enum in 886da190 of 0.3.0-redux branch. I'm hoping the compiler can optimize the switch away at compile time since all those functions are inlined, but if not, we could probably do something like template the `diffusion_mixing_rule` function on the switch parameter instead.
