### ISSUE TITLE
Support reaction chemistry in S3D

### ISSUE THREAD

**Issue by nicholasmalaya** [libantioch/antioch#20]
We want to enhance antioch to fully support the reaction chemistry in S3D. Using Jackie Chen's paper on [S3d](http://iopscience.iop.org/1749-4699/2/1/015001) as a model document, we the following capabilities: 

* Mixture-averaged diffusion coef. determined from binary diffusion coef and the mixture composition. 
* Only treat (N-1) species, with the last coming from constraint (e.g. \sum Y_i = 1)

S3D assumes an ideal gas mixture, so the equation of state is all set. I need to read through the documentation more carefully, and then will propose Antioch files to modify.

**Comment by SylvainPlessis** [comment]
Isn't this the whole transport PR craziness?

Shouldn't we delete this issue?

**Comment by nicholasmalaya** [comment]
Yes. This issue is deprecated. Might be worth plopping a few references to the actual tickets that resolved this issue before closing it, however.

**Comment by SylvainPlessis** [comment]
Done.
