### ISSUE TITLE
API Consistency Between IdealGasMicroThermo and StatMechThermodynamics

### ISSUE THREAD

**Issue by pbauman** [libantioch/antioch#238]
Right now, we don't have complete consistency in the API between these two classes, even though the intent is that they be used interchangeably. For example, cv(), cp(), cv_el(), and probably more, are missing from `IdealGasMicroThermo` but are present in `StatMechThermodynamics`.

I'm thinking we introduce a `MicroThermoBase` CRTP base class and have each of `IdealGasMicroThermo` and `StatMechThermodynamics` appropriately subclass.

**Comment by roystgnr** [comment]
Sounds good to me.

**Comment by pbauman** [comment]
Addressed in #240.
