### ISSUE TITLE
Add API for getting species cp from StatMechThermo

### ISSUE THREAD

**Issue by pbauman** [libantioch/antioch#37]
Looks like we have species cv there, but not cp. Would be useful to have in the API. @nicholasmalaya volunteered to implement this.

**Comment by SylvainPlessis** [comment]
Any objection to removing this?  The micro thermo is taken care of, cp is computed through cv - R (and yes, this is the universal R, I'm not more being polite :bowtie:) in the ```IdealGasMicroThermo``` object, left to the user for ```StatMechThermo```.
