### ISSUE TITLE
Rethink ParticleFlux Handling?

### ISSUE THREAD

**Issue by pbauman** [libantioch/antioch#58]
I admit ignorance in what the ParticleFlux stuff is doing, but it is potentially taking away thread safety.

So *Mixture classes are intended to be "program constant" classes while *Evaluators are (intended to be) lightweight objects that are cheap to construct (from the *Mixture classes) so that we construct *Mixtures once and *Evaluators many times (e.g. once a thread is forked). However, at least in the case of Planet-INC/Planet_INC, the particle flux pointer is getting reset many times during the program lifetime and, in particular, will be reset by multiple threads at once leading to thread safety problems.

Is there anyway we can move the ParticleFlux business up to the KineticsEvaluator level? It looks like the ParticleFlux is being used to augment the reaction rate - can't we just do that in the KineticsEvaluator when the rate is actually used?

**Comment by SylvainPlessis** [comment]
I guess now this one is obsolete too, isn't it?

**Comment by SylvainPlessis** [comment]
Obsolete, closing it
