### ISSUE TITLE
NASA polynomials

### ISSUE THREAD

**Issue by SylvainPlessis** [libantioch/antioch#80]
Another API change possible here...

The current CEA curve fit is one case of the NASA polynomials, the question is, at the mixture and evaluator levels, do we keep the "cea" name?

A more correct name would be nasa_mixture and nasa_evaluator, then you define the type of polynomials you want (CEA or NASA) but that would make another API change.

By the way, those two models are indeed different polynomials, it is not only a question of generalizing the temperatures and the number of intervals; CEA being a NASA 9 polynomials, the "classical" (understand ChemKin, see for instance [Berkeley combustion](http://combustion.berkeley.edu/Combustion_Laboratory/gri-mech/data/nasa_plnm.html)) one being a NASA 7 polynomial.

So?

**Comment by pbauman** [comment]
Hmm, starting to look at this and the corresponding PR #81. I wonder then should we have a `NASA9Polynomial` and `NASA7Polynomial`?

**Comment by SylvainPlessis** [comment]
It depends how we want the name to stand for.  From a strictly technical point of view, NASA9 and NASA7 should be prefered, from a more model-description point of view, NASA and CEA are more adapted.

A nice way to not choose would be a typedef :)

**Comment by pbauman** [comment]
I'd prefer `NASA9` and `NASA7` because I'll forget otherwise. We can put in the class documentation that NASA9 -> CEA and NASA7 -> ChemKin or whatever. I'm not inclined to have there be typedefs globally in the library for this, but we could put them in examples.

**Comment by SylvainPlessis** [comment]
Should we change also the names of the files?

**Comment by roystgnr** [comment]
Whatever we do let's leave some shims (with deprecation warnings) in?  I'm in the middle of setting up a forward-compatibility PR since a prior filename change means that GRINS currently doesn't even compile against the current Antioch head.

**Comment by SylvainPlessis** [comment]
I think I would prefer to actually keep the names of the files as is.  In this case, the objects have the technical more rigorous name, but the files have a somewhat more physical-friendly name.

This PR is supposed to be entirely backward compatible with previous thermo, with now the exception of the CEA vs NASA9 name.

I think I'll add an _examples_ folder (in some other PR to be created) where we can explain & show the ```typedef```s play to make life easier.

**Comment by SylvainPlessis** [comment]
This is obsolete, closing it.
