### ISSUE TITLE
reset_coefs and const rate types

### ISSUE THREAD

**Issue by beanSnippet** [libantioch/antioch#85]
I'm getting some strange output while trying to use reset_coefs(). I will try to give you all the relevant pieces.

This is the line in my code, where i is an unsigned int and newValues is a standard vector of doubles:

reaction_set.reaction(i).forward_rate().reset_coefs(newValues);

This is (part of) the compile time error:

/workspace/rebeccam/bin/antioch-kin_reset/include/antioch/kinetics_type.h:398:86: error: passing ‘const Antioch::KooijRate<double>’ as ‘this’ argument of ‘void Antioch::KooijRate<CoeffType>::reset_coefs(const VectorCoeffType&) [with VectorCoeffType = std::vector<double>, CoeffType = double]’ discards qualifiers [-fpermissive]

It also returns the same error for all the other rate types (even though I'm not using them). I know that the test passes, so I'm not sure where the problem is. But here is some speculation: the method in reset_coefs is not const, but kinetics_type.h returns a const object of type KooijRate. However, in the test, KooijRate is not defined as a const, so it still works there.

See [here](https://github.com/libantioch/antioch/blob/master/src/kinetics/include/antioch/kinetics_type.h#L197).

**Comment by SylvainPlessis** [comment]
Resetting the kinetics is done, closing it.
